import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.io.IOException;

import java.util.stream.Stream;
import java.util.*;

public class TrafficLoader
{

	//VERY hacky but desperate times...
	private static class Counter
	{
		private int idx = 0;

		public void inc()
		{
			++idx;
		}

		public int getIdx()
		{
			return idx;
		}
	}

	private static class TrafficContainer
	{
		public final int linkId; //link ID => line number
		public final String node1;
		public final String node2;

		private List<String> traff = new ArrayList<>();
		public TrafficContainer(int linkId, String n1, String n2)
		{
			this.linkId = linkId;
			this.node1 = n1;
			this.node2 = n2;
		}

		public void addTraffic(String str)
		{
			traff.add(str);
		}
	}

	//Key: <node1><space><node2>
	//Val: TrafficContainer
	private static Map<String, TrafficContainer> linkIDMap = new HashMap<>();
	private static final Counter counter = new Counter();

	//Input: p count
	public static void main(String[] args) throws Exception
	{
	//	int p = Integer.parseInt(args[0]);
	//	String trafficFileName = args[1]; //File generated by UniversalTrafficGenerator
	//	String model = args[2]; 
		
		toLinkTraffic("foobar", 1);
	}

	private static void constrIDMap(String topoFile)
		throws IOException
	{
		Path file = Paths.get(topoFile);

		Stream<String> lines = Files.lines(file);
		lines.forEach(line -> {
			String[] toks = line.split("\\s+");
			//Load the map
			linkIDMap.put(line, new TrafficContainer(counter.getIdx(), toks[0], toks[1]));
			counter.inc();
		});
	}

	/**
	 * Generate p files ea file containing the traffic data for that proc
     * Requirement: LP-on-ea-proc files have already been generated
     * Ea line containing
	 */
	private static void toLinkTraffic(String trafficFile, int p)
		throws IOException
	{	
		//Read the topo file to construct the ID map
		constrIDMap("g1000_5");
		
		//Read from the traffic file
		Path file = Paths.get(trafficFile);	

		Stream<String> lines = Files.lines(file);

		//Ea line's format: <start node id> <next node id> <start time> <stop count == num node>
		lines.forEach(line -> {
			String[] toks = line.split("\\s+");
					
			TrafficContainer cont = linkIDMap.get(String.format("%s %s", toks[0], toks[1]));
			
			//TODO: make sure ea link aware of the nodes it connects
			
		});

	}

	/**
     * Genera
	 */
	private static void loadNodeTraffic(String trafficFile, int p)
	{
	}
	
}
